shop/dbshop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.search, name='search'),
    path("search", views.search),
    path("create", views.create, name='create'),
    path('<int:pk>', views.GoodsDetailView.as_view(), name='goods-detail'),
    path('<int:pk>/update', views.GoodsUpdateView.as_view(), name='goods-update'),
    path('<int:pk>/delete', views.GoodsDeleteView.as_view(), name='goods-delete')
]

shop/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name='home'),
    path("about/", views.about, name='about'),
    path("error/", views.error, name='error')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("main.urls")),
    path("admin/", admin.site.urls),
    path("shopping/", include("dbshop.urls")),
    path("user/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/users/urls.py
from django.urls import path
from django.urls import include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include('django.contrib.auth.urls')),
    path("sign-up", views.sign_up, name='sign-up'),
]

shop/dbshop/models.py
from django.db import models


class Goods(models.Model):
    title = models.CharField('Name', max_length=50)
    description = models.TextField('Description', max_length=2000)
    created = models.DateTimeField('Created at', auto_now_add=True)
    updated = models.DateTimeField('Last updated')
    author = models.CharField('Created by', max_length=50)
    pic = models.ImageField('Picture of a good', default='404.webp', upload_to='uploads')
    price = models.FloatField('Price in USD')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/shopping/{self.id}'

    class Meta:
        verbose_name = 'Good'
        verbose_name_plural = 'Goods'

shop/main/models.py
from django.db import models

# Create your models here.

shop/dbshop/forms.py
from .models import Goods
from django.forms import ModelForm, TextInput, Textarea, DateTimeInput


class GoodsForm(ModelForm):
    class Meta:
        model = Goods
        fields = ['title', 'description', 'price', 'updated', 'pic', 'author']

        labels = {
            'title': '',
            'description': '',
            'price': '',
            'updated': '',
            'pic': '',
            'author': '',
            }

        widgets = {
            "title": TextInput(attrs={'class': 'form-control', 'placeholder': 'Name of good'}),
            "description": Textarea(attrs={'class': 'form-control', 'placeholder': 'Description of a good'}),
            "price": TextInput(attrs={'class': 'form-control', 'placeholder': 'Price in USD'}),
            "updated": DateTimeInput(attrs={'class': 'form-control', 'placeholder': 'Current date and time'}),
            "author": DateTimeInput(attrs={'class': 'form-control', 'placeholder': 'Your login'}),
        }

shop/users/forms.py
from django.forms import TextInput
from django import forms
from django.contrib.auth.forms import UserCreationForm, User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    default_currency = forms.CharField(required=True)
    default_language = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'default_currency', 'default_language', 'email']

        labels = {
            'username': '',
            'password': '',
            'default_language': '',
            'default_currency': '',
            }

        widgets = {
            "username": TextInput(attrs={'class': 'form-control', 'placeholder': 'Login'}),
            "password1": TextInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
            "password2": TextInput(attrs={'class': 'form-control', 'placeholder': 'Repeat it'}),
            "email": TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            "default_currency": TextInput(attrs={'class': 'form-control', 'placeholder': 'UAH, PLN, EUR or USD'}),
            "default_language": TextInput(attrs={'class': 'form-control', 'placeholder': 'UA or EN'}),
        }

shop/dbshop/views.py
from django.shortcuts import render, redirect
from .models import Goods
from .forms import GoodsForm
from django.views.generic import DetailView, UpdateView, DeleteView
from datetime import datetime
from django.db import models


def search(request):
    good = Goods.objects.order_by('title')
    return render(request, 'dbshop/search.html', {'good': good})


class GoodsDetailView(DetailView):
    model = Goods
    template_name = 'dbshop/detail_view.html'
    context_object_name = 'good'


class GoodsUpdateView(UpdateView):
    model = Goods
    template_name = 'dbshop/create.html'
    form_class = GoodsForm


class GoodsDeleteView(DeleteView):
    model = Goods
    success_url = '/shopping'
    template_name = 'dbshop/delete.html'


def create(request):
    error = ''
    if request.method == 'POST':
        form = GoodsForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.updated = datetime.now()
            form.save()
            return redirect('home')
        else:
            error = "Invalid form!"
    form = GoodsForm()
    data = {
        'form': form,
        'error': error,
    }
    return render(request, 'dbshop/create.html', data)

shop/main/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return render(request, 'main/home.html')


def about(request):
    return render(request, 'main/about.html')

def error(request):
    return render(request, 'main/error.html')

shop/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import RegistrationForm


def sign_up(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/home')
    else:
        form = RegistrationForm()

    return render(request, "registration/sign_up.html", {"form": form})

shop/dbshop/templates/dbshop/create.html
{% extends 'main/layout.html' %}
{% load updated %}

{% block title %}Create advertisement{% endblock %}

{% block content %}
    <b>Create advertisement</b>
    <form method="post" enctype="multipart/form-data">
        {% if error != '' %}
            <div class="alert alert-danger">
                <span>{{ error }}</span>
            </div><br>
        {% endif %}
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.price }}<br>
        <div class="picSelector">{{ form.pic }}</div>
        <br>
        {{ form.description }}<br>
        <input type="hidden" name="author" id="id_author" value='{{ form.author }}'>
        <input type="hidden" name="updated" id="id_updated" value='{{ form.updated }}'>
        {% if user.is_authenticated %}
            <button class="btn btn-success" onclick="setUpdatedDate()" type="submit">Publish advertisement</button>
        {% else %}
            <h3>You can not sell until You <a href="{% url 'login' %}">log in</a></h3>
        {% endif %}
    </form>

    <script>
        function setUpdatedDate() {
            document.getElementById('id_updated').value = '{% updated %}';
            document.getElementById('id_author').value = '{{ user.username }}';
        }
    </script>
{% endblock %}

shop/dbshop/templates/dbshop/delete.html
{% extends 'main/layout.html' %}

{% block title %}Delete advertisement{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Delete</button>
    </form>
{% endblock %}

shop/dbshop/templates/dbshop/detail_view.html
{% extends 'main/layout.html' %}
{% load exchange %}


{% block title %}{{ good.title }}{% endblock %}

{% block content %}
    <h1>{{ good.title }}</h1>
    <img src="{{ good.pic.url }}" width=500><br>
    <div id="exchanger">
        <div id="moneyAmount" data-good-price="{{ good.price|default:0 }}"></div>
        <select class="form-control" id = 'currency' onchange="performExchange()">
            <option value="UAH" {% if user.default_currency == 'UAH' %}selected{% endif %} >UAH</option>
            <option value="PLN" {% if user.default_currency == 'PLN' %}selected{% endif %} >PLN</option>
            <option value="USD" {% if user.default_currency == 'USD' %}selected{% endif %} >USD</option>
            <option value="EUR" {% if user.default_currency == 'EUR' %}selected{% endif %} >EUR</option>
        </select>

        <h3 id="result"></h3>
        <script src="/static/js/exchanger.js" defer></script>

    </div>
    <h2>{{ good.description }}</h2>
    <h3>Last updated at {{ good.updated }}</h3>
    <h3>Published at {{ good.created }} by {{ good.author }}</h3>
    {% if user.is_authenticated and user.username == good.author %}
        <a href = "{% url 'goods-update' good.id %}" class="btn btn-warning">Edit</a>
        <a href = "{% url 'goods-delete' good.id %}" class="btn btn-warning">Delete</a>
    {% elif user.is_authenticated and user.username != good.author %}
        <a href = "{% url 'error' %}" class="btn btn-warning">Buy</a>
    {% else %}
        <h3>You can not buy anything unless You <a href="{% url 'login' %}">log in</a></h3>
    {% endif %}
    {{ user.default_currency }}
{% endblock %}

shop/dbshop/templates/dbshop/search.html
{% extends 'main/layout.html' %}
{% load exchange %}

{% block title %}Search{% endblock %}

{% block content %}
    <b>Search</b><br>
    {% if good %}
        {% for el in good %}
            <div class="alert alert-warning">
                <h3>{{ el.title}}</h3>
                <img src="{{ el.pic.url }}" height=260><br>
                <h3>{{el.price}} USD</h3>
                <a href="{% url 'goods-detail' el.id %}" class="btn btn-warning">Read more</a>
            </div>
        {% endfor %}
    {% else %}
        <b>Nothing here yet</b>
    {% endif %}
{% endblock %}

shop/main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <h3>This is my IPPT project, not an actual shop</h3>
    <b>If You noticed issues, please report to </b>
    <a href="https://github.com/ndrnmnk/ippt-projects/issues">my GitHub</a>
{% endblock %}

shop/main/templates/main/error.html
{% extends 'main/layout.html' %}

{% block title %}Error{% endblock %}

{% block content %}
    <h3>You did something, that caused a shop to stop working (or page you was going to does not exist). </h3>
    <b>Please report your actions to </b><a href="https://github.com/ndrnmnk/ippt-projects/issues">GitHub.</a>
{% endblock %}

shop/main/templates/main/home.html
{% extends 'main/layout.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}
    <h1>Homepage</h1>
    <p>What should I put here?</p>
    <div class="sponsors">
        <h5>Our sponsors:</h5>
        <img src="/static/main/img/sponsors/nintendo.png">
        <img src="/static/main/img/sponsors/cocacola.svg">
        <img src="/static/main/img/sponsors/minecraft.png">
        <img src="/static/main/img/sponsors/amazon.png">
        <img src="/static/main/img/sponsors/lebigovych.webp">
        <br>
        <img src="/static/main/img/sponsors/rozetka.png">
        <img src="/static/main/img/sponsors/steam.png">
    </div>
{% endblock %}

shop/main/templates/main/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.4.2/css/all.css">
</head>
<body>
    <aside>
        <img src="{% static 'main/img/logo.png' %}" alt="Logo">
        <span class="logo">Shop</span><br>
        <ul>
            <a href="{% url 'home' %}"><li><i class="fa-solid fa-house-chimney"></i> Home</li></a>
            <a href="{% url 'about' %}"><li><i class="fa-solid fa-question"></i> About</li></a>
            <a href="{% url 'search' %}"><li><i class="fa-solid fa-magnifying-glass"></i>Search</a>
            <a href="{% url 'create' %}"><li><i class="fa-solid fa-plus"></i>Sell</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"><li><i class="fa-solid fa-right-to-bracket"></i>Log out</a>
                <b>Logged as {{user.username}}
            {% else %}
                <a href="{% url 'login' %}"><li><i class="fa-solid fa-right-to-bracket"></i>Log in</a>
            {% endif %}
        </ul>
    </aside>
    <main>
        <div class="features">
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>
</html>